M48
; DRILL file {KiCad 6.0.10-86aedd382b~118~ubuntu18.04.1} date Thu 08 Jun 2023 12:44:20 PM PDT
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-06-08T12:44:20-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.10-86aedd382b~118~ubuntu18.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0472
%
G90
G05
T1
X6.1006Y-3.9884
T0
M30
